version: '3.7'

volumes:
  logs:
    driver: local

services:
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    container_name: qrl_virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso.qrl:/data/virtuoso.qrl
    ports:
      - "8890:8890"
  php_qrl:
    build: .
    container_name: qrl_php
    volumes:
      - .:/virtuoso_qrl
    command: tail -f /dev/null